services:
  mc:
    image: itzg/minecraft-server:java21-jdk
    container_name: mc
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    env_file:
      - .env
    environment:
      # ----------------------- General
      INIT_MEMORY: 16G
      MAX_MEMORY: 24G
      TZ: America/Sao_Paulo
      USE_MEOWICE_FLAGS: TRUE
      REMOVE_OLD_MODS: TRUE
      # ----------------------- Server
      TYPE: FABRIC
      EULA: TRUE
      VERSION: 1.21.8
      DIFFICULTY: normal
      ENABLE_COMMAND_BLOCK: FALSE
      MODE: survival
      FORCE_GAMEMODE: TRUE
      SPAWN_PROTECTION: 0
      DUMP_SERVER_PROPERTIES: TRUE
      # ----------------------- Allow List
      EXISTING_WHITELIST_FILE: SYNCHRONIZE
      ENFORCE_WHITELIST: TRUE
      # ----------------------- RCON
      ENABLE_RCON: ${ENABLE_RCON:-TRUE}
      RCON_PASSWORD: ${RCON_PASSWORD:?Set RCON_PASSWORD in .env}
      RCON_PORT: ${RCON_PORT:-25575}
    stop_grace_period: 1m
    volumes:
      - ./data:/data
    restart: unless-stopped

  backup:
    image: itzg/mc-backup
    container_name: mc-backup
    depends_on:
      - mc
    environment:
      TZ: America/Sao_Paulo
      # ----------------------- RCON
      RCON_HOST: mc
      RCON_PASSWORD: ${RCON_PASSWORD:?Set RCON_PASSWORD in .env}
      RCON_PORT: ${RCON_PORT:-25575}
      # ----------------------- Config
      BACKUP_INTERVAL: 1h
      BACKUP_ON_STARTUP: TRUE
      PRUNE_BACKUPS_DAYS: 14
    volumes:
      - ./data:/data:ro
      - ./backups:/backups
    restart: unless-stopped
